apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t01
  namespace: zkw56994
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: zkw56994
  destination:
    name: argus
    namespace: zkw56994
  source:
    path: apps
    repoURL: https://github.com/hyperrealist/t01-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
